/* ═══ Pin Board ═══════════════════════════════════════════════════════════
   Vanilla JS, no build step, no dependencies. Works from file:// and from
   GitHub Pages alike — catalog data is a plain <script> assigning globals so
   there is no fetch() and therefore no CORS problem when opened locally.

   Two separate data layers, deliberately:
     CATALOG  — researched reference data, read-only, regenerated by
                tools/build_catalog.py from the research JSON.
     MINE     — this browser's personal collection state (owned, paid, notes),
                kept in localStorage and exportable to JSON.
   Nothing in MINE is ever written back into CATALOG.
   ═══════════════════════════════════════════════════════════════════════ */

const CATALOG = (window.PIN_CATALOG || []).slice();
const SOURCES = window.PIN_SOURCES || { sources: [] };
const META = window.PIN_CATALOG_META || {};
const MINE_KEY = 'pinboard.mine.v1';
const PREF_KEY = 'pinboard.prefs.v1';

const RARITY_ORDER = ['common', 'uncommon', 'rare', 'very-rare', 'grail'];

/* ── persistence ─────────────────────────────────────────────────────────── */
let MINE = load(MINE_KEY, {});
let PREFS = load(PREF_KEY, {});

function load(key, fallback) {
  try { return JSON.parse(localStorage.getItem(key)) ?? fallback; }
  catch { return fallback; }
}
function save(key, val) {
  try { localStorage.setItem(key, JSON.stringify(val)); } catch {}
}
const mineOf = id => MINE[id] || {};
function setMine(id, patch) {
  MINE[id] = { ...mineOf(id), ...patch };
  // drop entries that carry no information, so exports stay clean
  const m = MINE[id];
  const empty = Object.values(m).every(v => v === '' || v === false || v == null);
  if (empty) delete MINE[id];
  save(MINE_KEY, MINE);
}

/* ── derived values ──────────────────────────────────────────────────────── */
/* Where an estimated value comes from, most trusted first:
     1. a value you typed yourself
     2. the median of sold comps YOU logged — your own observations beat
        researched ranges, and unlike raw eBay medians they aren't dragged
        down by the counterfeit ("scrapper") price cluster
     3. the researched median
     4. the midpoint of the researched range                                */
function valueSource(p) {
  const m = mineOf(p.id);
  if (num(m.myValue) != null) return { value: num(m.myValue), from: 'your valuation' };
  const cm = compsMedian(p.id);
  if (cm != null) {
    const n = (m.comps || []).length;
    return { value: cm, from: `median of your ${n} logged comp${n === 1 ? '' : 's'}` };
  }
  if (num(p.market_median_usd) != null) return { value: num(p.market_median_usd), from: 'researched median' };
  const lo = num(p.market_low_usd), hi = num(p.market_high_usd);
  if (lo != null && hi != null) return { value: (lo + hi) / 2, from: 'midpoint of researched range' };
  const one = lo ?? hi;
  return one != null ? { value: one, from: 'single researched figure' } : { value: null, from: null };
}
const marketValue = p => valueSource(p).value;

function compsMedian(id) {
  const xs = (mineOf(id).comps || []).map(c => num(c.price)).filter(v => v != null).sort((a, b) => a - b);
  if (!xs.length) return null;
  const mid = Math.floor(xs.length / 2);
  return xs.length % 2 ? xs[mid] : (xs[mid - 1] + xs[mid]) / 2;
}
function num(v) {
  if (v === '' || v == null) return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}
const isOwned = p => !!mineOf(p.id).owned;
const isWanted = p => !!mineOf(p.id).wishlist;
const money = v => v == null ? '—' : '$' + Number(v).toLocaleString('en-US',
  { minimumFractionDigits: v % 1 ? 2 : 0, maximumFractionDigits: 2 });

/* Placeholder art: a glyph picked from what the pin actually is. Replaced by a
   real cutout as soon as `image` is populated on the record. */
/* Who it is beats what shape it is — otherwise a shelf of ear-headband pins all
   render as the same bow. Character rules are tried first, then pin form. */
const CHAR_RULES = [
  [/cheshire/i, '😼'],
  [/alice|wonderland|mad tea|caterpillar/i, '🫖'],
  [/ariel|mermaid|flounder|sebastian/i, '🧜'],
  [/stitch|lilo/i, '👽'],
  [/elsa|anna|olaf|frozen|arendelle/i, '❄️'],
  [/pascal|rapunzel|tangled/i, '🦎'],
  [/nala|simba|lion king|zazu/i, '🦁'],
  [/dumbo/i, '🐘'],
  [/bambi/i, '🦌'],
  [/donald/i, '🦆'],
  [/daisy duck/i, '🌸'],
  [/goofy/i, '🐶'],
  [/pluto/i, '🐕'],
  [/marie|figaro|duchess/i, '🐈'],
  [/pooh|piglet|eeyore|tigger/i, '🍯'],
  [/jungle book|baloo|mowgli/i, '🐅'],
  [/gus|jaq|cinderella/i, '🐭'],
  [/orange bird/i, '🐦'],
  [/maleficent|ursula|evil queen|hades|jafar|villain|leota/i, '😈'],
  [/snow white|dopey|grumpy|dwarf/i, '🍎'],
  [/belle|beast|lumiere/i, '🌹'],
  [/jasmine|aladdin|genie/i, '🧞'],
  [/tiana|moana|merida|mulan|pocahontas|aurora|princess/i, '👑'],
  [/steamboat willie/i, '🚢'],
  [/minnie/i, '🎀'],
  [/mickey/i, '🐭'],
  [/star tours|star wars|jedi|vader|droid|r2|bb-8|boba fett/i, '🌌'],
  [/marvel|spider|iron man|thor|avenger/i, '🦸'],
  [/luna|spectrespecs/i, '👓'],
  [/weasley/i, '🎆'],
  [/gryffindor/i, '🦁'],
  [/slytherin/i, '🐍'],
  [/hufflepuff/i, '🦡'],
  [/ravenclaw/i, '🦅'],
  [/sorting hat/i, '🎩'],
  [/owl post|owl|hedwig/i, '🦉'],
  [/knight bus/i, '🚌'],
  [/chocolate frog/i, '🐸'],
  [/leaky cauldron|cauldron|potion/i, '⚗️'],
  [/flying key|winged key/i, '🗝️'],
  [/marauder|mischief/i, '👣'],
  [/platform 9|hogwarts express|hogwarts railway/i, '🚂'],
];
const FORM_RULES = [
  [/castle/i, '🏰'],
  [/boba|bubble tea|tea latte|drink|soda/i, '🧋'],
  [/sushi/i, '🍣'],
  [/popcorn/i, '🍿'],
  [/pretzel|churro|ice cream|cupcake|donut|treat|snack|food/i, '🍡'],
  [/bookmark|tassel/i, '🔖'],
  [/firework|nighttime|finale/i, '🎆'],
  [/haunted mansion|ghost|hatbox/i, '👻'],
  [/pirate/i, '🏴‍☠️'],
  [/space mountain|rocket|tomorrowland/i, '🚀'],
  [/big thunder|railroad/i, '🚂'],
  [/jungle cruise|tiki/i, '🌴'],
  [/small world|carrousel|carousel/i, '🎠'],
  [/peter pan|flight/i, '🧚'],
  [/balloon/i, '🎈'],
  [/cruise|ship|boat/i, '🚢'],
  [/flower|garden|floral|blossom/i, '🌼'],
  [/museum/i, '🏛️'],
  [/anniversary|50th|disney100|disney 100/i, '✨'],
  [/letter|alphabet|monogram|initial|'d' pin/i, '🔤'],
  [/ticket/i, '🎫'],
  [/crest|alumni|badge|shield|banner/i, '🛡️'],
  [/ear headband|headband|minnie ear/i, '🎀'],
  [/wand/i, '🪄'],
  [/snowflake|ornament/i, '❄️'],
  [/keychain|keyring/i, '🔑'],
];
function glyph(p) {
  const hay = [p.name, p.series, p.property, (p.characters || []).join(' '),
               (p.tags || []).join(' '), p.board_note].filter(Boolean).join(' ');
  for (const [re, g] of CHAR_RULES) if (re.test(hay)) return g;
  for (const [re, g] of FORM_RULES) if (re.test(hay)) return g;
  return p.franchise === 'Wizarding World' ? '⚡' : '📌';
}
const TACKS = ['#d94f4f', '#3f7fd9', '#4fae72', '#e0a53c', '#9b62c9', '#d9578f'];
const tackColor = p => TACKS[Math.abs(hash(p.id)) % TACKS.length];
function hash(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return h;
}

/* ── search index ────────────────────────────────────────────────────────── */
CATALOG.forEach(p => {
  p._hay = [
    p.name, p.series, p.property, p.franchise, p.origin, p.park_specific,
    p.edition_type, p.pin_type && p.pin_type.join(' '), p.rarity, p.year,
    (p.characters || []).join(' '), (p.tags || []).join(' '), p.notes,
    p.pinpics_id, p.sku, p.board_note,
  ].filter(Boolean).join(' ').toLowerCase();
});

/* ── facet definitions ──────────────────────────────────────────────────── */
const FACETS = [
  { key: 'franchise',    label: 'Franchise',    get: p => p.franchise },
  { key: 'series',       label: 'Series',       get: p => p.series },
  { key: 'origin',       label: 'Origin',       get: p => p.origin },
  { key: 'edition_type', label: 'Edition',      get: p => p.edition_type },
  { key: 'rarity',       label: 'Rarity',       get: p => p.rarity },
  { key: 'pin_type',     label: 'Pin type',     get: p => p.pin_type || [] },
  { key: 'characters',   label: 'Character',    get: p => p.characters || [] },
  { key: 'property',     label: 'Property',     get: p => p.property },
  { key: 'status',       label: 'My status',    get: p => {
      const out = [];
      if (isOwned(p)) out.push('Owned');
      if (isWanted(p)) out.push('On want list');
      if (!isOwned(p) && !isWanted(p)) out.push('Untracked');
      if (p.on_board) out.push('On the real board');
      return out;
    } },
];

/* ── table columns ──────────────────────────────────────────────────────── */
const COLUMNS = [
  { key: 'name',        label: 'Name',          def: true,  get: p => p.name, cls: 'wrap' },
  { key: 'franchise',   label: 'Franchise',     def: true,  get: p => p.franchise },
  { key: 'property',    label: 'Property',      def: true,  get: p => p.property },
  { key: 'series',      label: 'Series',        def: true,  get: p => p.series, cls: 'wrap' },
  { key: 'series_position', label: '# in set',  def: false, get: p => p.series_position },
  { key: 'characters',  label: 'Characters',    def: false, get: p => (p.characters || []).join(', ') },
  { key: 'year',        label: 'Year',          def: true,  get: p => p.year, cls: 'num' },
  { key: 'release_date', label: 'Released',     def: false, get: p => p.release_date },
  { key: 'origin',      label: 'Origin',        def: true,  get: p => p.origin },
  { key: 'park_specific', label: 'Park / shop', def: false, get: p => p.park_specific },
  { key: 'edition_type', label: 'Edition',      def: true,  get: p => p.edition_type },
  { key: 'edition_size', label: 'LE size',      def: true,  get: p => p.edition_size, cls: 'num' },
  { key: 'pin_type',    label: 'Pin type',      def: false, get: p => (p.pin_type || []).join(', ') },
  { key: 'size_mm',     label: 'Size (mm)',     def: false, get: p => p.size_mm },
  { key: 'backstamp',   label: 'Backstamp',     def: false, get: p => p.backstamp },
  { key: 'rarity',      label: 'Rarity',        def: true,  get: p => p.rarity },
  { key: 'retired',     label: 'Retired',       def: false, get: p => p.retired == null ? null : (p.retired ? 'yes' : 'no') },
  { key: 'retail_price_usd', label: 'Retail',   def: true,  get: p => p.retail_price_usd, cls: 'num', fmt: money },
  { key: 'market_low_usd',    label: 'Mkt low',  def: true,  get: p => p.market_low_usd, cls: 'num', fmt: money },
  { key: 'market_median_usd', label: 'Mkt med',  def: true,  get: p => p.market_median_usd, cls: 'num', fmt: money },
  { key: 'market_high_usd',   label: 'Mkt high', def: true,  get: p => p.market_high_usd, cls: 'num', fmt: money },
  { key: 'value',       label: 'Est. value',    def: true,  get: p => marketValue(p), cls: 'num', fmt: money },
  { key: 'premium',     label: 'vs retail',     def: false, get: p => {
      const v = marketValue(p), r = num(p.retail_price_usd);
      return (v != null && r) ? Math.round((v / r) * 100) / 100 : null;
    }, cls: 'num', fmt: v => v == null ? '—' : v.toFixed(2) + '×' },
  { key: 'price_confidence', label: 'Price conf.', def: false, get: p => p.price_confidence },
  { key: 'confidence',  label: 'ID conf.',      def: false, get: p => p.confidence },
  { key: 'pinpics_id',  label: 'PinPics #',     def: false, get: p => p.pinpics_id },
  { key: 'sku',         label: 'SKU',           def: false, get: p => p.sku },
  { key: 'tags',        label: 'Tags',          def: false, get: p => (p.tags || []).join(', '), cls: 'wrap' },
  { key: 'on_board',    label: 'On board',      def: false, get: p => p.on_board ? '✓' : '' },
  { key: 'board_note',  label: 'Board position', def: false, get: p => p.board_note, cls: 'wrap' },
  /* personal columns */
  { key: 'owned',       label: 'Owned',         def: true,  get: p => isOwned(p) ? '✓' : '', mine: true },
  { key: 'qty',         label: 'Qty',           def: false, get: p => mineOf(p.id).qty, cls: 'num', mine: true },
  { key: 'condition',   label: 'Condition',     def: false, get: p => mineOf(p.id).condition, mine: true },
  { key: 'backerCard',  label: 'Backer card',   def: false, get: p => mineOf(p.id).backerCard, mine: true },
  { key: 'compCount',   label: 'My comps',      def: false, get: p => (mineOf(p.id).comps || []).length || null, cls: 'num', mine: true },
  { key: 'compMedian',  label: 'My comp median', def: false, get: p => compsMedian(p.id), cls: 'num', fmt: money, mine: true },
  { key: 'paid',        label: 'Paid',          def: false, get: p => num(mineOf(p.id).paid), cls: 'num', fmt: money, mine: true },
  { key: 'gain',        label: 'Gain/loss',     def: false, get: p => {
      const v = marketValue(p), paid = num(mineOf(p.id).paid);
      return (v != null && paid != null) ? v - paid : null;
    }, cls: 'num', fmt: money, mine: true },
  { key: 'acquired',    label: 'Acquired',      def: false, get: p => mineOf(p.id).acquired, mine: true },
  { key: 'acquiredFrom', label: 'Acquired from', def: false, get: p => mineOf(p.id).acquiredFrom, mine: true },
  { key: 'myValue',     label: 'My value',      def: false, get: p => num(mineOf(p.id).myValue), cls: 'num', fmt: money, mine: true },
  { key: 'wishlist',    label: 'Want',          def: false, get: p => isWanted(p) ? '✓' : '', mine: true },
  { key: 'target',      label: 'Target $',      def: false, get: p => num(mineOf(p.id).target), cls: 'num', fmt: money, mine: true },
  { key: 'myNotes',     label: 'My notes',      def: false, get: p => mineOf(p.id).notes, cls: 'wrap', mine: true },
  { key: 'notes',       label: 'Catalog notes', def: false, get: p => p.notes, cls: 'wrap' },
];

/* ── UI state ───────────────────────────────────────────────────────────── */
const state = {
  view: 'board',
  q: '',
  sort: PREFS.sort || 'name',
  filters: {},
  yearMin: null, yearMax: null, valMin: null, valMax: null,
  boardFilter: 'all',
  page: 1,
  perPage: 60,
  cols: new Set(PREFS.cols || COLUMNS.filter(c => c.def).map(c => c.key)),
  tableSort: PREFS.tableSort || { key: 'name', dir: 1 },
};
FACETS.forEach(f => state.filters[f.key] = new Set());

const $  = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
const el = (tag, props = {}, kids = []) => {
  const n = Object.assign(document.createElement(tag), props);
  (Array.isArray(kids) ? kids : [kids]).forEach(k => k != null &&
    n.appendChild(typeof k === 'string' ? document.createTextNode(k) : k));
  return n;
};

/* ── filtering ──────────────────────────────────────────────────────────── */
function activeFilterCount() {
  let n = Object.values(state.filters).reduce((a, s) => a + s.size, 0);
  ['yearMin', 'yearMax', 'valMin', 'valMax'].forEach(k => { if (state[k] != null) n++; });
  return n;
}

function matches(p) {
  if (state.q) {
    const toks = state.q.toLowerCase().split(/\s+/).filter(Boolean);
    if (!toks.every(t => p._hay.includes(t))) return false;
  }
  for (const f of FACETS) {
    const sel = state.filters[f.key];
    if (!sel.size) continue;
    const v = f.get(p);
    const vals = Array.isArray(v) ? v : [v];
    if (!vals.some(x => sel.has(x))) return false;
  }
  const y = num(p.year);
  if (state.yearMin != null && (y == null || y < state.yearMin)) return false;
  if (state.yearMax != null && (y == null || y > state.yearMax)) return false;
  const v = marketValue(p);
  if (state.valMin != null && (v == null || v < state.valMin)) return false;
  if (state.valMax != null && (v == null || v > state.valMax)) return false;
  return true;
}

function sortPins(list, mode) {
  const by = {
    name:    (a, b) => (a.name || '').localeCompare(b.name || ''),
    year:    (a, b) => (num(a.year) ?? 9e9) - (num(b.year) ?? 9e9),
    value:   (a, b) => (marketValue(a) ?? -1) - (marketValue(b) ?? -1),
    rarity:  (a, b) => RARITY_ORDER.indexOf(a.rarity) - RARITY_ORDER.indexOf(b.rarity),
    series:  (a, b) => (a.series || 'zzz').localeCompare(b.series || 'zzz') ||
                       (a.series_position || '').localeCompare(b.series_position || ''),
  };
  const desc = mode.startsWith('-');
  const key = desc ? mode.slice(1) : mode;
  const cmp = by[key] || by.name;
  return list.slice().sort((a, b) => (desc ? -1 : 1) * cmp(a, b) || by.name(a, b));
}

const filtered = () => CATALOG.filter(matches);

/* ── render: facets ─────────────────────────────────────────────────────── */
function renderFacets() {
  const base = filtered();
  const grid = $('#filters-grid');
  grid.textContent = '';
  for (const f of FACETS) {
    const counts = new Map();
    for (const p of base) {
      const v = f.get(p);
      for (const x of (Array.isArray(v) ? v : [v])) {
        if (x == null || x === '') continue;
        counts.set(x, (counts.get(x) || 0) + 1);
      }
    }
    // selected values must stay visible even at count 0
    for (const s of state.filters[f.key]) if (!counts.has(s)) counts.set(s, 0);
    if (!counts.size) continue;

    const order = f.key === 'rarity'
      ? [...counts.keys()].sort((a, b) => RARITY_ORDER.indexOf(a) - RARITY_ORDER.indexOf(b))
      : [...counts.keys()].sort((a, b) => counts.get(b) - counts.get(a) || String(a).localeCompare(String(b)));

    const list = el('div', { className: 'facet-list' });
    for (const v of order.slice(0, 60)) {
      const on = state.filters[f.key].has(v);
      const b = el('button', { className: 'chip', type: 'button' });
      b.setAttribute('aria-pressed', on);
      b.append(document.createTextNode(String(v) + ' '), el('span', { className: 'n', textContent: counts.get(v) }));
      b.onclick = () => {
        on ? state.filters[f.key].delete(v) : state.filters[f.key].add(v);
        state.page = 1; renderAll();
      };
      list.appendChild(b);
    }
    grid.appendChild(el('div', { className: 'facet' }, [el('h4', { textContent: f.label }), list]));
  }
  const n = activeFilterCount();
  const badge = $('#filter-count');
  badge.hidden = !n;
  badge.textContent = n;
}

/* ── render: cork board ─────────────────────────────────────────────────── */
function renderBoard() {
  const cork = $('#cork');
  cork.querySelectorAll('.pinned, .board-group').forEach(n => n.remove());

  let owned = CATALOG.filter(isOwned);
  if (state.boardFilter !== 'all') owned = owned.filter(p => p.franchise === state.boardFilter);
  if (state.q || activeFilterCount()) owned = owned.filter(matches);

  $('#cork-empty').hidden = owned.length > 0;

  const groups = new Map();
  for (const p of owned) {
    const g = p.franchise || 'Other';
    if (!groups.has(g)) groups.set(g, []);
    groups.get(g).push(p);
  }
  const order = ['Wizarding World', 'Disney', 'Pixar', 'Star Wars', 'Marvel'];
  const keys = [...groups.keys()].sort((a, b) => {
    const ia = order.indexOf(a), ib = order.indexOf(b);
    return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b);
  });

  for (const k of keys) {
    if (keys.length > 1) cork.appendChild(el('div', { className: 'board-group', textContent: k }));
    for (const p of sortPins(groups.get(k), 'series')) cork.appendChild(pinnedNode(p));
  }

  /* Research identified pins physically on the board; offer to claim them in
     one go rather than making the owner tick 50-odd boxes by hand. */
  const unclaimed = CATALOG.filter(p => p.on_board && !isOwned(p));
  const banner = $('#claim-banner');
  banner.hidden = unclaimed.length === 0;
  $('#claim-count').textContent = unclaimed.length;

  /* Say plainly how much of the total is actually backed by price data —
     "$0 total" across 53 unpriced pins would read as a valuation, not a gap. */
  const withVal = owned.filter(p => marketValue(p) != null);
  const total = withVal.reduce((a, p) => a + marketValue(p), 0);
  const n = owned.length;
  let caption = '';
  if (n) {
    caption = `${n} pin${n === 1 ? '' : 's'} on the board · `;
    caption += withVal.length === 0
      ? 'none priced yet — open a pin and run a price check'
      : `${money(Math.round(total))} across the ${withVal.length} with a value on record` +
        (withVal.length < n ? ` · ${n - withVal.length} still unpriced` : '');
  }
  $('#board-caption').textContent = caption;
}

function pinnedNode(p) {
  const art = el('span', { className: 'art' });
  if (p.image) art.appendChild(el('img', { src: p.image, alt: p.name, loading: 'lazy' }));
  else art.appendChild(el('span', { className: 'glyph', textContent: glyph(p) }));
  const tack = el('span', { className: 'tack' });
  tack.style.setProperty('--tack', tackColor(p));
  const b = el('button', { className: 'pinned', type: 'button', title: p.name },
    [tack, art, el('span', { className: 'plabel', textContent: shortName(p) })]);
  b.onclick = () => openDrawer(p);
  return b;
}
function shortName(p) {
  let s = (p.name || '').replace(/^Disney\s+/i, '');
  // trim a redundant trailing "Pin"/"Pin Set", but never down to a stub
  const trimmed = s.replace(/\s*pin(\s+set)?\s*$/i, '');
  if (trimmed.length >= 12) s = trimmed;
  return s.slice(0, 42);
}

/* ── render: card grid ──────────────────────────────────────────────────── */
function cardNode(p) {
  const art = el('span', { className: 'card-art' });
  if (p.image) art.appendChild(el('img', { src: p.image, alt: '', loading: 'lazy' }));
  else art.textContent = glyph(p);

  const badges = el('div', { className: 'badges' });
  if (p.rarity) badges.appendChild(el('span', { className: 'badge rare-' + p.rarity, textContent: p.rarity }));
  if (p.edition_type) badges.appendChild(el('span', { className: 'badge', textContent: p.edition_type + (p.edition_size ? ' ' + p.edition_size.toLocaleString() : '') }));
  if (isOwned(p)) badges.appendChild(el('span', { className: 'badge own', textContent: 'owned' }));
  if (isWanted(p)) badges.appendChild(el('span', { className: 'badge want', textContent: 'want' }));

  const v = marketValue(p);
  const lo = num(p.market_low_usd), hi = num(p.market_high_usd);
  const priceEl = v == null
    ? el('span', { className: 'price none', textContent: 'no comps yet' })
    : el('span', { className: 'price' }, [
        document.createTextNode(money(Math.round(v))),
        (lo != null && hi != null) ? el('span', { className: 'range', textContent: ` ${money(lo)}–${money(hi)}` }) : null,
      ]);

  const sub = [p.series, p.year, p.origin].filter(Boolean).join(' · ');
  const card = el('button', { className: 'card', type: 'button' }, [
    el('div', { className: 'card-top' }, [
      art,
      el('div', {}, [el('h3', { textContent: p.name }), el('div', { className: 'sub', textContent: sub })]),
    ]),
    badges,
    el('div', { className: 'card-foot' }, [priceEl, el('span', { className: 'muted small', textContent: p.franchise })]),
  ]);
  card.onclick = () => openDrawer(p);
  return card;
}

function renderGrid() {
  const list = sortPins(filtered(), state.sort);
  const grid = $('#grid');
  grid.textContent = '';
  const slice = list.slice(0, state.page * state.perPage);
  slice.forEach(p => grid.appendChild(cardNode(p)));
  $('#grid-empty').hidden = list.length > 0;
  $('#btn-more').hidden = list.length <= slice.length;
  $('#result-count').textContent =
    `${list.length.toLocaleString()} of ${CATALOG.length.toLocaleString()} pins`;
}

function renderWishlist() {
  const list = sortPins(CATALOG.filter(p => isWanted(p) && matches(p)), state.sort);
  const grid = $('#wl-grid');
  grid.textContent = '';
  list.forEach(p => {
    const c = cardNode(p);
    const t = num(mineOf(p.id).target), v = marketValue(p);
    if (t != null && v != null && v <= t) {
      c.querySelector('.badges').appendChild(
        el('span', { className: 'badge own', textContent: `at target ${money(t)}` }));
    } else if (t != null) {
      c.querySelector('.badges').appendChild(
        el('span', { className: 'badge', textContent: `target ${money(t)}` }));
    }
    grid.appendChild(c);
  });
  $('#wl-empty').hidden = list.length > 0;
}

/* ── render: table ──────────────────────────────────────────────────────── */
function visibleCols() { return COLUMNS.filter(c => state.cols.has(c.key)); }

function renderColPicker() {
  const panel = $('#colpick-panel');
  panel.textContent = '';
  for (const c of COLUMNS) {
    const cb = el('input', { type: 'checkbox', checked: state.cols.has(c.key) });
    cb.onchange = () => {
      cb.checked ? state.cols.add(c.key) : state.cols.delete(c.key);
      PREFS.cols = [...state.cols]; save(PREF_KEY, PREFS);
      renderTable();
    };
    panel.appendChild(el('label', {}, [cb, document.createTextNode(c.label + (c.mine ? ' ★' : ''))]));
  }
}

function renderTable() {
  const cols = visibleCols();
  const head = $('#thead-row');
  head.textContent = '';
  for (const c of cols) {
    const th = el('th', { textContent: c.label });
    if (state.tableSort.key === c.key) {
      th.appendChild(el('span', { className: 'arrow', textContent: state.tableSort.dir > 0 ? ' ▲' : ' ▼' }));
    }
    th.onclick = () => {
      state.tableSort = state.tableSort.key === c.key
        ? { key: c.key, dir: -state.tableSort.dir }
        : { key: c.key, dir: 1 };
      PREFS.tableSort = state.tableSort; save(PREF_KEY, PREFS);
      renderTable();
    };
    head.appendChild(th);
  }

  const col = COLUMNS.find(c => c.key === state.tableSort.key) || COLUMNS[0];
  const rows = filtered().sort((a, b) => {
    const va = col.get(a), vb = col.get(b);
    const na = num(va), nb = num(vb);
    let r;
    if (na != null && nb != null) r = na - nb;
    else if (va == null || va === '') r = vb == null || vb === '' ? 0 : 1;   // blanks last
    else if (vb == null || vb === '') r = -1;
    else r = String(va).localeCompare(String(vb));
    return r * state.tableSort.dir || (a.name || '').localeCompare(b.name || '');
  });

  const tb = $('#tbody');
  tb.textContent = '';
  const frag = document.createDocumentFragment();
  for (const p of rows.slice(0, 600)) {
    const tr = el('tr');
    for (const c of cols) {
      const raw = c.get(p);
      const txt = c.fmt ? c.fmt(raw) : (raw == null || raw === '' ? '—' : String(raw));
      const td = el('td', { className: c.cls || '', textContent: txt });
      if (txt === '✓') td.className += ' tick';
      tr.appendChild(td);
    }
    tr.onclick = () => openDrawer(p);
    frag.appendChild(tr);
  }
  tb.appendChild(frag);
  $('#result-count').textContent =
    `${rows.length.toLocaleString()} of ${CATALOG.length.toLocaleString()} pins` +
    (rows.length > 600 ? ' · showing first 600' : '');
}

/* ── render: stats ──────────────────────────────────────────────────────── */
function renderStats() {
  const owned = CATALOG.filter(isOwned);
  const want = CATALOG.filter(isWanted);
  const val = owned.reduce((a, p) => a + (marketValue(p) ?? 0), 0);
  const paid = owned.reduce((a, p) => a + (num(mineOf(p.id).paid) ?? 0), 0);
  const priced = CATALOG.filter(p => marketValue(p) != null).length;

  const ownedPriced = owned.filter(p => marketValue(p) != null).length;
  const stats = [
    ['Pins in catalog', CATALOG.length.toLocaleString()],
    ['Owned', owned.length.toLocaleString()],
    ['On want list', want.length.toLocaleString()],
    ['Value of priced pins', ownedPriced ? money(Math.round(val)) : 'none priced', true],
    ['Owned pins priced', owned.length ? `${ownedPriced} of ${owned.length}` : '—'],
    ['Total paid', paid ? money(Math.round(paid)) : '—'],
    ['Unrealised gain', paid && ownedPriced ? money(Math.round(val - paid)) : '—'],
    ['Catalog with price data', `${Math.round(priced / Math.max(CATALOG.length, 1) * 100)}%`],
    ['Series tracked', new Set(CATALOG.map(p => p.series).filter(Boolean)).size],
  ];
  const row = $('#stat-row');
  row.textContent = '';
  stats.forEach(([k, v, gold]) => row.appendChild(
    el('div', { className: 'stat' }, [
      el('div', { className: 'k', textContent: k }),
      el('div', { className: 'v' + (gold ? ' gold' : ''), textContent: v }),
    ])));

  bars('#bar-franchise', p => p.franchise);
  bars('#bar-edition', p => p.edition_type);
  bars('#bar-origin', p => p.origin);
  bars('#bar-decade', p => num(p.year) ? `${Math.floor(num(p.year) / 10) * 10}s` : null);
}

function bars(sel, getter) {
  const counts = new Map();
  for (const p of CATALOG) {
    const v = getter(p);
    if (!v) continue;
    counts.set(v, (counts.get(v) || 0) + 1);
  }
  const rows = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 12);
  const max = Math.max(1, ...rows.map(r => r[1]));
  const host = $(sel);
  host.textContent = '';
  rows.forEach(([k, n]) => {
    const fill = el('div', { className: 'bar-fill' });
    fill.style.width = (n / max * 100).toFixed(1) + '%';
    host.appendChild(el('div', { className: 'bar-row' }, [
      el('span', { className: 'lbl', textContent: k, title: k }),
      el('div', { className: 'bar-track' }, fill),
      el('span', { className: 'n', textContent: n }),
    ]));
  });
}

/* ── price link building ────────────────────────────────────────────────── */
function searchTerms(p) {
  const bits = [p.name];
  if (p.series && !new RegExp(escapeRe(p.series), 'i').test(p.name)) bits.push(p.series);
  const q = bits.join(' ')
    .replace(/[—–]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const tight = /disney|wizarding|hogwarts|harry potter/i.test(q) ? q : q + ' Disney pin';
  return tight;
}
const escapeRe = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function priceLinks(p) {
  const q = encodeURIComponent(searchTerms(p));
  const img = p.image ? encodeURIComponent(absoluteUrl(p.image)) : null;
  return (SOURCES.sources || [])
    // reverse-image lookups are only meaningful once the pin has a picture
    .filter(s => !s.needs_image || img)
    .map(s => ({
      name: s.name,
      kind: s.kind,
      url: s.url_template.replace(/\{QUERY\}/g, q).replace(/\{IMAGE_URL\}/g, img || ''),
      primary: s.kind === 'sold-comps',
    }));
}
function absoluteUrl(u) {
  try { return new URL(u, location.href).href; } catch { return u; }
}

/* ── drawer ─────────────────────────────────────────────────────────────── */
let drawerPin = null;

function openDrawer(p) {
  drawerPin = p;
  const body = $('#drawer-body');
  body.textContent = '';

  const art = el('div', { className: 'd-art' });
  if (p.image) art.appendChild(el('img', { src: p.image, alt: '' }));
  else art.textContent = glyph(p);

  body.appendChild(el('div', { className: 'd-head' }, [
    art,
    el('div', {}, [
      el('h2', { textContent: p.name }),
      el('div', { className: 'd-sub', textContent: [p.series, p.series_position, p.year].filter(Boolean).join(' · ') }),
      (() => {
        const badges = el('div', { className: 'badges', style: 'margin-top:.4rem' });
        if (p.rarity) badges.appendChild(el('span', { className: 'badge rare-' + p.rarity, textContent: p.rarity }));
        if (p.confidence) badges.appendChild(el('span', { className: 'badge', textContent: 'ID: ' + p.confidence }));
        if (p.on_board) badges.appendChild(el('span', { className: 'badge own', textContent: 'on your board' }));
        return badges;
      })(),
    ]),
  ]));

  /* value */
  const vs = valueSource(p);
  const v = vs.value;
  const lo = num(p.market_low_usd), hi = num(p.market_high_usd);
  const pb = el('div', { className: 'pricebox' }, [
    el('span', { className: 'big', textContent: v == null ? '—' : money(Math.round(v)) }),
    (lo != null || hi != null)
      ? el('span', { className: 'lo-hi', textContent: `${money(lo)} – ${money(hi)}` }) : null,
    p.price_confidence
      ? el('span', { className: 'conf ' + p.price_confidence, textContent: p.price_confidence + ' confidence' }) : null,
  ]);
  const valueSection = el('div', { className: 'd-section' }, [el('h3', { textContent: 'Estimated value' }), pb]);
  if (vs.from) {
    valueSection.appendChild(el('p', { className: 'note muted small', textContent: 'Based on: ' + vs.from }));
  }
  if (v == null) {
    valueSection.appendChild(el('p', { className: 'note muted',
      textContent: 'No value on record for this pin. Run a price check below, then log what you find — logged comps become the estimate.' }));
  } else if (p.price_confidence === 'low' && !compsMedian(p.id) && num(mineOf(p.id).myValue) == null) {
    valueSection.appendChild(el('p', { className: 'note muted',
      textContent: 'Treat this as a rough hint only. Raw marketplace medians run low because counterfeits cluster at the bottom of the range — log a real comp to replace it.' }));
  }
  body.appendChild(valueSection);

  /* price checks */
  const links = el('div', { className: 'linkgrid' });
  priceLinks(p).forEach(l => links.appendChild(
    el('a', { href: l.url, target: '_blank', rel: 'noopener noreferrer',
              className: l.primary ? 'primary' : '' },
      [document.createTextNode(l.name), el('span', { className: 'arrow', textContent: '↗' })])));
  body.appendChild(el('div', { className: 'd-section' }, [
    el('h3', { textContent: 'Check the price now' }),
    links,
    el('p', { className: 'note muted small', style: 'margin-top:.5rem',
      textContent: 'Sold-listing searches are the reliable ones — active asking prices run high.' }),
  ]));

  /* my copy */
  const m = mineOf(p.id);
  const ownBtn = el('button', { className: 'btn tiny' + (m.owned ? ' gold' : ''), type: 'button',
    textContent: m.owned ? '✓ I own this' : 'I own this' });
  ownBtn.onclick = () => { setMine(p.id, { owned: !mineOf(p.id).owned }); openDrawer(p); renderAll(); };
  const wantBtn = el('button', { className: 'btn tiny' + (m.wishlist ? ' gold' : ''), type: 'button',
    textContent: m.wishlist ? '✓ On want list' : 'Want it' });
  wantBtn.onclick = () => { setMine(p.id, { wishlist: !mineOf(p.id).wishlist }); openDrawer(p); renderAll(); };

  /* Condition and backer card are separate on purpose: collectors price them
     separately. A damaged pin loses 40–70%; losing only the special backer
     card can still cost ~50% on its own. */
  const mineRows = [
    ['Quantity', 'qty', 'number'],
    ['Condition', 'condition', 'select',
      ['', 'Mint', 'Very good', 'Good', 'Worn', 'Damaged', 'Suspected scrapper']],
    ['Backer card', 'backerCard', 'select',
      ['', 'On original card', 'Special backer card', 'Card only, pin loose', 'No card', 'Unknown']],
    ['Paid ($)', 'paid', 'number'],
    ['Acquired', 'acquired', 'date'],
    ['Acquired from', 'acquiredFrom', 'text'],
    ['My value ($)', 'myValue', 'number'],
    ['Target ($)', 'target', 'number'],
  ];
  const mine = el('div', { className: 'mine' });
  mine.appendChild(el('div', { className: 'own-toggles' }, [ownBtn, wantBtn]));
  for (const [label, key, type, opts] of mineRows) {
    let input;
    if (type === 'select') {
      input = el('select');
      opts.forEach(o => input.appendChild(el('option', { value: o, textContent: o || '—' })));
      input.value = m[key] || '';
    } else {
      input = el('input', { type, value: m[key] ?? '' });
      if (type === 'number') input.min = '0';
    }
    input.onchange = () => { setMine(p.id, { [key]: input.value }); renderAll(); };
    mine.appendChild(el('div', { className: 'mine-row' }, [el('label', { textContent: label }), input]));
  }
  const notes = el('textarea', { rows: 3, value: m.notes || '', placeholder: 'Where you got it, trade history, condition detail…' });
  notes.onchange = () => { setMine(p.id, { notes: notes.value }); renderAll(); };
  mine.appendChild(el('div', { className: 'mine-row' }, [el('label', { textContent: 'My notes' }), notes]));
  body.appendChild(el('div', { className: 'd-section' }, [el('h3', { textContent: 'My copy' }), mine]));

  /* ── sold-comp log ──────────────────────────────────────────────────────
     No public API returns Disney pin sold prices, so the only way to own real
     price data is to record it as you see it. These accumulate per pin and the
     median becomes the estimate. */
  const comps = (mineOf(p.id).comps || []).slice()
    .sort((a, b) => String(b.date || '').localeCompare(String(a.date || '')));
  const compSection = el('div', { className: 'd-section' },
    el('h3', { textContent: 'Sold comps I have logged' }));

  if (comps.length) {
    const med = compsMedian(p.id);
    const prices = comps.map(c => num(c.price)).filter(v2 => v2 != null);
    compSection.appendChild(el('p', { className: 'note muted small', textContent:
      `${comps.length} comp${comps.length === 1 ? '' : 's'} · median ${money(med)}` +
      (prices.length > 1 ? ` · range ${money(Math.min(...prices))}–${money(Math.max(...prices))}` : '') }));
    const ul = el('ul', { className: 'complist' });
    comps.forEach(c => {
      const del = el('button', { className: 'comp-del', type: 'button', title: 'Remove this comp', textContent: '✕' });
      del.onclick = e => {
        e.stopPropagation();
        const rest = (mineOf(p.id).comps || []).filter(x => x !== c);
        setMine(p.id, { comps: rest });
        openDrawer(p); renderAll();
      };
      ul.appendChild(el('li', {}, [
        el('span', { className: 'comp-price', textContent: money(num(c.price)) }),
        el('span', { className: 'comp-meta', textContent: [c.date, c.source, c.note].filter(Boolean).join(' · ') }),
        del,
      ]));
    });
    compSection.appendChild(ul);
  } else {
    compSection.appendChild(el('p', { className: 'note muted small',
      textContent: 'Nothing logged yet. When you see this pin actually sell, record the price — your own comps are better data than any researched range.' }));
  }

  const cPrice  = el('input', { type: 'number', min: '0', step: '0.01', placeholder: 'Price $' });
  const cDate   = el('input', { type: 'date', value: new Date().toISOString().slice(0, 10) });
  const cSource = el('select');
  ['eBay sold', 'Mercari', 'Etsy', 'Pin trader', 'Facebook group', 'Reddit', 'In park', 'Other']
    .forEach(o => cSource.appendChild(el('option', { value: o, textContent: o })));
  const cNote = el('input', { type: 'text', placeholder: 'Note (condition, on card…)' });
  const cAdd  = el('button', { className: 'btn tiny gold', type: 'button', textContent: 'Log comp' });
  cAdd.onclick = () => {
    const price = num(cPrice.value);
    if (price == null) { cPrice.focus(); return; }
    const list = (mineOf(p.id).comps || []).concat([{
      price, date: cDate.value || null, source: cSource.value, note: cNote.value || null,
    }]);
    setMine(p.id, { comps: list });
    openDrawer(p); renderAll();
  };
  cPrice.onkeydown = e => { if (e.key === 'Enter') cAdd.click(); };
  compSection.appendChild(el('div', { className: 'compform' }, [cPrice, cDate, cSource, cNote, cAdd]));
  body.appendChild(compSection);

  /* full record */
  const facts = [
    ['Franchise', p.franchise], ['Property', p.property],
    ['Series', p.series], ['Position in set', p.series_position],
    ['Characters', (p.characters || []).join(', ')],
    ['Year', p.year], ['Release date', p.release_date],
    ['Origin', p.origin], ['Park / shop', p.park_specific],
    ['Edition', p.edition_type],
    ['Edition size', p.edition_size ? p.edition_size.toLocaleString() : null],
    ['Pin type', (p.pin_type || []).join(', ')],
    ['Size', p.size_mm], ['Backstamp', p.backstamp],
    ['Retail price', p.retail_price_usd != null ? money(p.retail_price_usd) : null],
    ['Retired', p.retired == null ? null : (p.retired ? 'Yes' : 'No')],
    ['PinPics #', p.pinpics_id], ['SKU', p.sku],
    ['On your board', p.on_board ? (p.board_note || 'Yes') : null],
  ].filter(([, v2]) => v2 != null && v2 !== '');
  const dl = el('dl', { className: 'kv' });
  facts.forEach(([k, v2]) => { dl.appendChild(el('dt', { textContent: k })); dl.appendChild(el('dd', { textContent: String(v2) })); });
  body.appendChild(el('div', { className: 'd-section' }, [el('h3', { textContent: 'Catalog record' }), dl]));

  if (p.notes) {
    body.appendChild(el('div', { className: 'd-section' }, [
      el('h3', { textContent: 'Notes' }), el('p', { className: 'note', textContent: p.notes })]));
  }
  if ((p.tags || []).length) {
    const row = el('div', { className: 'tagrow' });
    p.tags.forEach(t => {
      const b = el('button', { className: 'chip', type: 'button', textContent: t });
      b.onclick = () => { closeDrawer(); state.q = t; $('#q').value = t; setView('browse'); renderAll(); };
      row.appendChild(b);
    });
    body.appendChild(el('div', { className: 'd-section' }, [el('h3', { textContent: 'Tags' }), row]));
  }

  /* provenance */
  const srcs = el('ul', { className: 'srclist' });
  (p.price_sources || []).forEach(s => srcs.appendChild(el('li', {}, [
    s.url ? el('a', { href: s.url, target: '_blank', rel: 'noopener noreferrer', textContent: s.name || s.url })
          : el('span', { textContent: s.name || 'source' }),
    el('span', { className: 'muted small', textContent: [s.date, s.note].filter(Boolean).join(' · ') ? ` — ${[s.date, s.note].filter(Boolean).join(' · ')}` : '' }),
  ])));
  (p.source_urls || []).forEach(u => srcs.appendChild(el('li', {}, [
    el('a', { href: u, target: '_blank', rel: 'noopener noreferrer', textContent: prettyHost(u) })])));
  if (srcs.children.length) {
    body.appendChild(el('div', { className: 'd-section' }, [
      el('h3', { textContent: 'Where this data came from' }), srcs]));
  }

  $('#drawer').hidden = false;
  $('#scrim').hidden = false;
  document.body.style.overflow = 'hidden';
  $('#drawer').scrollTop = 0;
}
function prettyHost(u) {
  try { return new URL(u).hostname.replace(/^www\./, ''); } catch { return u; }
}
function closeDrawer() {
  $('#drawer').hidden = true;
  $('#scrim').hidden = true;
  document.body.style.overflow = '';
  drawerPin = null;
}

/* ── CSV ────────────────────────────────────────────────────────────────── */
function downloadCSV() {
  const cols = visibleCols();
  const esc = v => {
    const s = v == null ? '' : String(v);
    return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
  };
  const lines = [cols.map(c => esc(c.label)).join(',')];
  for (const p of filtered()) lines.push(cols.map(c => esc(c.get(p))).join(','));
  download('pin-catalog.csv', lines.join('\n'), 'text/csv');
}
function download(name, text, type) {
  const url = URL.createObjectURL(new Blob([text], { type: type + ';charset=utf-8' }));
  const a = el('a', { href: url, download: name });
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/* ── views / wiring ─────────────────────────────────────────────────────── */
function setView(v) {
  state.view = v;
  $$('.tab').forEach(t => t.classList.toggle('is-active', t.dataset.view === v));
  $$('.view').forEach(s => s.classList.toggle('is-active', s.id === 'view-' + v));
  renderAll();
}

function renderAll() {
  renderFacets();
  if (state.view === 'board') renderBoard();
  if (state.view === 'browse') renderGrid();
  if (state.view === 'table') renderTable();
  if (state.view === 'wishlist') renderWishlist();
  if (state.view === 'stats') renderStats();
  if (state.view === 'board' || state.view === 'wishlist' || state.view === 'stats') {
    const n = filtered().length;
    $('#result-count').textContent = `${n.toLocaleString()} of ${CATALOG.length.toLocaleString()} pins match`;
  }
}

function wire() {
  $$('.tab').forEach(t => t.onclick = () => setView(t.dataset.view));

  const q = $('#q');
  let t = null;
  q.oninput = () => {
    clearTimeout(t);
    t = setTimeout(() => { state.q = q.value.trim(); state.page = 1; renderAll(); }, 120);
  };
  document.addEventListener('keydown', e => {
    if (e.key === '/' && document.activeElement !== q) { e.preventDefault(); q.focus(); q.select(); }
    if (e.key === 'Escape') { if (!$('#drawer').hidden) closeDrawer(); else if (document.activeElement === q) q.blur(); }
  });

  $('#btn-filters').onclick = () => { const f = $('#filters'); f.hidden = !f.hidden; };
  $('#btn-clear-filters').onclick = () => {
    FACETS.forEach(f => state.filters[f.key].clear());
    ['yearMin', 'yearMax', 'valMin', 'valMax'].forEach(k => state[k] = null);
    ['#year-min', '#year-max', '#val-min', '#val-max'].forEach(s => $(s).value = '');
    state.page = 1; renderAll();
  };
  const bind = (sel, key) => $(sel).oninput = () => { state[key] = num($(sel).value); state.page = 1; renderAll(); };
  bind('#year-min', 'yearMin'); bind('#year-max', 'yearMax');
  bind('#val-min', 'valMin');   bind('#val-max', 'valMax');

  $('#sort').value = state.sort;
  $('#sort').onchange = e => { state.sort = e.target.value; PREFS.sort = state.sort; save(PREF_KEY, PREFS); renderAll(); };

  $('#btn-more').onclick = () => { state.page++; renderGrid(); };
  $('#btn-csv').onclick = downloadCSV;

  $$('.seg-btn').forEach(b => b.onclick = () => {
    $$('.seg-btn').forEach(x => x.classList.toggle('is-active', x === b));
    state.boardFilter = b.dataset.board; renderBoard();
  });

  $('#btn-claim').onclick = () => {
    const todo = CATALOG.filter(p => p.on_board && !isOwned(p));
    if (!confirm(`Mark ${todo.length} pins from your board photo as owned?`)) return;
    todo.forEach(p => setMine(p.id, { owned: true }));
    renderAll();
  };

  $('#drawer-close').onclick = closeDrawer;
  $('#scrim').onclick = closeDrawer;

  $('#btn-export').onclick = () => download(
    `pin-collection-${new Date().toISOString().slice(0, 10)}.json`,
    JSON.stringify({ exported: new Date().toISOString(), version: 1, mine: MINE }, null, 2),
    'application/json');

  $('#btn-import').onclick = () => $('#file-import').click();
  $('#file-import').onchange = e => {
    const f = e.target.files[0];
    if (!f) return;
    const r = new FileReader();
    r.onload = () => {
      try {
        const data = JSON.parse(r.result);
        const incoming = data.mine || data;
        if (typeof incoming !== 'object' || Array.isArray(incoming)) throw new Error('unrecognised shape');
        const n = Object.keys(incoming).length;
        if (!confirm(`Import ${n} pin record${n === 1 ? '' : 's'}? This merges into what's already here.`)) return;
        MINE = { ...MINE, ...incoming };
        save(MINE_KEY, MINE);
        renderAll();
        alert(`Imported ${n} record${n === 1 ? '' : 's'}.`);
      } catch (err) {
        alert('Could not read that file: ' + err.message);
      }
      e.target.value = '';
    };
    r.readAsText(f);
  };

  const themeBtn = $('#theme-toggle');
  if (PREFS.theme) document.documentElement.dataset.theme = PREFS.theme;
  themeBtn.onclick = () => {
    const next = document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark';
    document.documentElement.dataset.theme = next;
    PREFS.theme = next; save(PREF_KEY, PREFS);
  };

  $('#foot-meta').textContent = [
    `${CATALOG.length} pins in catalog`,
    META.generated ? `catalog built ${META.generated}` : null,
    META.segments ? `${META.segments.length} research segments` : null,
  ].filter(Boolean).join(' · ');
}

renderColPicker();
wire();
setView('board');
